version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  db-volume:
  bundle-volume:
